function Praxis_Simulation()
    % mohamed made this :p
    % this is a backpack strap length analysis using a simplified (yet
    % research backed) model. 
    %
    % this code uses a simplified Euler–Bernoulli beam model of the lumbar spine
    % and the Moment-Area Theorems (MAT1 & MAT2) to estimate curvature /
    % deflection under backpack load.
    %
    % The spine is modelled as a homogeneous beam (lumbar spine, ~18 cm)
    % with constant flexural rigidity EI. E is taken from apparent
    % vertebral cortico-cancellous bone (El Masri et al., 2012) and I is
    % chosen so EI is in the range of lumbar bending stiffness reported by
    % Lee et al.
    %
    % PROTOTYPES:
    %  - Elastic Strap:
    %  - Inside-Bag Adjustment:
    %  - Shoulder-Side Adjustment:

    % main figure
    fig = figure('Name', 'Backpack Strap Spine Deviation Analysis', ...
                 'Units', 'normalized', ...
                 'Position', [0.05 0.05 0.9 0.85], ...
                 'Color', [0.12 0.13 0.15]);

    % Panel & axes
    controlPanel = uipanel('Parent', fig, ...
                          'Title', 'Input Parameters', ...
                          'Position', [0.02 0.02 0.25 0.96], ...
                          'BackgroundColor', [0.18 0.20 0.22], ...
                          'ForegroundColor', [0.9 0.9 0.95], ...
                          'FontSize', 11, 'FontWeight', 'bold');

    statsPanel = uipanel('Parent', fig, ...
                        'Title', 'Performance Metrics', ...
                        'Position', [0.72 0.08 0.26 0.87], ...
                        'BackgroundColor', [0.18 0.20 0.22], ...
                        'ForegroundColor', [0.9 0.9 0.95], ...
                        'FontSize', 11, 'FontWeight', 'bold');

    ax3d = axes('Parent', fig, 'Position', [0.30 0.55 0.40 0.40], ...
                'Color', [0.15 0.16 0.18], 'XColor', [0.7 0.7 0.75], ...
                'YColor', [0.7 0.7 0.75], 'ZColor', [0.7 0.7 0.75]);

    ax2d = axes('Parent', fig, 'Position', [0.30 0.08 0.40 0.40], ...
                'Color', [0.15 0.16 0.18], 'XColor', [0.7 0.7 0.75], ...
                'YColor', [0.7 0.7 0.75]);

    % Input parameters
    params = struct();
    yPos   = 0.92;
    deltaY = 0.08;

    % prototype selector 
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Prototype:', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.35 0.04], ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.design = uicontrol('Parent', controlPanel, 'Style', 'popupmenu', ...
              'String', {'Elastic Strap', ...
                         'Inside-Bag Adjustment', ...
                         'Shoulder-Side Adjustment'}, ...
              'Units', 'normalized', ...
              'Position', [0.40 yPos 0.55 0.05], ...
              'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], ...
              'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Excess strap length
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Excess Strap (cm):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.excessStrap = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '6', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Strap length range
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Range of Lengths (cm):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.strapLength = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '25.3', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Pack weight
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Pack Weight (kg):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.weight = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '15', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Strap tensile strength
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Tensile Strength (MPa):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.tensileStrength = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '17.5', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Shoulder pressure
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Shoulder Pressure (kPa):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.shoulderPressure = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '29.541', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Chest pressure
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Chest Pressure (Pa):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.chestPressure = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '0', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Additional components weight
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Additional Weight (kg):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.additionalWeight = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '0.05663', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Deformation after cycles \ not needed but is in our measurement
    % matrix, just put it as a statistic
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Deformation (cm):', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.deformation = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '1.846', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);
    yPos = yPos - deltaY;

    % Obstructed components \ not needed but is in our measurement
    % matrix, just put it as a statistic
    uicontrol('Parent', controlPanel, 'Style', 'text', ...
              'String', 'Obstructed Items:', ...
              'Units', 'normalized', 'Position', [0.05 yPos 0.6 0.04], ...
              'HorizontalAlignment', 'left', 'BackgroundColor', [0.18 0.20 0.22], ...
              'ForegroundColor', [0.85 0.85 0.9], 'FontSize', 9);
    params.obstructed = uicontrol('Parent', controlPanel, 'Style', 'edit', ...
              'String', '0', 'Units', 'normalized', ...
              'Position', [0.65 yPos 0.3 0.05], 'Callback', @updateSimulation, ...
              'BackgroundColor', [0.25 0.27 0.30], 'ForegroundColor', [0.95 0.95 1]);

    % Stats text display
    params.statsText = uicontrol('Parent', statsPanel, 'Style', 'text', ...
                                 'Units', 'normalized', ...
                                 'Position', [0.05 0.05 0.9 0.9], ...
                                 'HorizontalAlignment', 'left', ...
                                 'BackgroundColor', [0.12 0.13 0.15], ...
                                 'ForegroundColor', [0.85 0.90 0.95], ...
                                 'FontName', 'Consolas', ...
                                 'FontSize', 9.5);

    % Initial simulation
    updateSimulation();

    % updating values function
    function updateSimulation(~, ~)
        % Read inputs
        excessStrap  = str2double(get(params.excessStrap,  'String'));
        strapLength  = str2double(get(params.strapLength,  'String'));
        weight       = str2double(get(params.weight,       'String'));
        additionalWeight = str2double(get(params.additionalWeight, 'String'));
        totalWeight  = weight + additionalWeight;
        tensile      = str2double(get(params.tensileStrength, 'String'));
        shoulderPress = str2double(get(params.shoulderPressure, 'String'));
        chestPress   = str2double(get(params.chestPressure, 'String'));
        deform       = str2double(get(params.deformation, 'String'));
        obstruct     = str2double(get(params.obstructed,  'String'));

        designIdx    = get(params.design, 'Value');

        % Spine parameters (fixed for all prototypes)
        spineLength = 18;        % cm
        E_spine     = 7.91e8;    % Pa
        I_spine     = 2e-8;      % m^4

        % moment arm depending on design
        switch designIdx
            case 1  % Elastic Strap
                baseDistance = 22;    % cm 
            case 2  % Inside-Bag Adjustment
                baseDistance = 10.5;  % cm
            case 3  % Shoulder-Side Adjustment
                baseDistance = 9.5;   % cm
        end

        % baseDistance is measured from spine to pack COM without excess strap.
        loadDistance = baseDistance + excessStrap * 0.5;  % cm

        momentScale = 1.0;
        M0 = momentScale * totalWeight * 9.81 * (loadDistance / 100); % N·m

        % MAT 1 & 2
        x = linspace(0, spineLength, 100);  

        % decaying moment toward upper end of segment
        M_dist = M0 * (1 - x / spineLength).^2.2;   % N·m

        % MAT1
        theta = zeros(size(x));  % rad
        for i = 2:length(x)
            dx_cm = x(i) - x(i-1);
            dx_m  = dx_cm / 100;
            kappa = M_dist(i) / (E_spine * I_spine);   % 1/m
            theta(i) = theta(i-1) + kappa * dx_m;
        end

        % MAT2
        deflection_cm = zeros(size(x));
        for i = 2:length(x)
            dx_cm = x(i) - x(i-1);
            deflection_cm(i) = deflection_cm(i-1) + theta(i) * dx_cm;
        end

        theta_deg         = rad2deg(theta);
        max_deflection_cm = max(abs(deflection_cm));
        max_angle_deg     = max(abs(theta_deg));

        % Requirement R1: COM deviation < 1 cm
        meetsR1 = max_deflection_cm < 1.0;
        if meetsR1
            r1Text = 'YES (meets R1: < 1 cm)';
        else
            r1Text = 'NO  (violates R1: ≥ 1 cm)';
        end
        r1TextPadded = sprintf('%-20s', r1Text);

        % efficiency + safety factor
        efficiency = 100 * (1 - excessStrap / strapLength);
        strapArea  = 0.0001; % m^2 (typical strap cross-section)
        strapStress = (totalWeight * 9.81) / strapArea / 1e6; % MPa
        safetyFactor = tensile / strapStress;
        strapForce = totalWeight * 9.81; % N

        % 3D PLOT
        axes(ax3d); cla; hold on;

        % Create meshgrid for surface plot showing deviation "field" -
        % scale is upped to be able to view it properly
        [X_grid, Y_grid] = meshgrid( ...
            linspace(min(deflection_cm)-1, max(deflection_cm)+1, 30), ...
            linspace(0, spineLength, 30));

        Z_grid = zeros(size(X_grid));
        for i = 1:size(X_grid, 1)
            for j = 1:size(X_grid, 2)
                y_pos = Y_grid(i, j);
                x_pos = X_grid(i, j);
                % find closest spine position
                [~, idx] = min(abs(x - y_pos));
                deviation_at_y = deflection_cm(idx);
                % Gaussian field around the deviation curve, scaled 0–1 (i
                % love matlab)
                Z_grid(i, j) = exp(-((x_pos - deviation_at_y)^2) / 1.5) * ...
                               (y_pos / spineLength);
            end
        end

        % smooth field surface (semi-transparent)
        s1 = surf(X_grid, Y_grid, Z_grid, ...
                  'EdgeColor', 'none', 'FaceAlpha', 0.65);

        % main deviation "tube" (spine centerline)
        [theta_tube, r_tube] = meshgrid(linspace(0, 2*pi, 16), [0, 0.25]);
        X_tube = zeros(length(x), size(theta_tube, 2));
        Y_tube = zeros(length(x), size(theta_tube, 2));
        Z_tube = zeros(length(x), size(theta_tube, 2));
        for i = 1:length(x)
            for j = 1:size(theta_tube, 2)
                X_tube(i, j) = deflection_cm(i) + r_tube(2) * cos(theta_tube(1, j));
                Y_tube(i, j) = x(i);
                Z_tube(i, j) = r_tube(2) * sin(theta_tube(1, j));
            end
        end

        color_vals = abs(deflection_cm) / max(abs(deflection_cm) + 1e-6);
        tube_colors = zeros(length(x), size(theta_tube, 2), 3);
        for i = 1:length(x)
            tube_colors(i, :, 1) = 0.2 + 0.7 * color_vals(i);  % R
            tube_colors(i, :, 2) = 0.5 - 0.3 * color_vals(i);  % G
            tube_colors(i, :, 3) = 0.9 - 0.5 * color_vals(i);  % B
        end

        s2 = surf(X_tube, Y_tube, Z_tube, tube_colors, ...
                  'EdgeColor', 'none', 'FaceAlpha', 0.95);

        % Simple neutral spine reference line at x = 0 (centre)
        plot3(zeros(size(x)), x, zeros(size(x)), '--', ...
              'Color', [0.6 0.6 0.65], 'LineWidth', 2);

        % Colorbar 
        colormap(ax3d, [linspace(0.2, 0.9, 256)', ...
                        linspace(0.5, 0.3, 256)', ...
                        linspace(0.9, 0.4, 256)']);
        cb = colorbar(ax3d);
        cb.Label.String = 'Relative deviation intensity';
        cb.Color = [0.9 0.9 0.95];

        xlabel('Lateral Deflection (cm)', 'Color', [0.85 0.85 0.9], ...
               'FontSize', 11, 'FontWeight', 'bold');
        ylabel('Spine Position (cm)', 'Color', [0.85 0.85 0.9], ...
               'FontSize', 11, 'FontWeight', 'bold');
        zlabel('Field (normalized)', 'Color', [0.85 0.85 0.9], ...
               'FontSize', 11, 'FontWeight', 'bold');
        title('3D Deviation Field Around Loaded Lumbar Spine', ...
              'FontWeight', 'bold', 'Color', [0.9 0.9 0.95], 'FontSize', 13);

        grid on;
        set(gca, 'GridColor', [0.4 0.4 0.45], 'GridAlpha', 0.4);
        set(gca, 'Color', [0.10 0.11 0.13]);
        camlight('right'); camlight('left');
        lighting gouraud; material(s2, 'shiny');

        % Make everything somewhat nicely visible (i tried my best this
        % probably took th longest to get right)
        view(-35, 25);
        axis tight;
        rotate3d on;

        hold off;

        %  2D sideview plot
        axes(ax2d); cla;
        fill([deflection_cm, fliplr(zeros(size(x)))], ...
             [x, fliplr(x)], ...
             [0.4 0.6 0.9], 'FaceAlpha', 0.3, 'EdgeColor', 'none'); hold on;
        plot(deflection_cm, x, 'Color', [0.4 0.7 1], 'LineWidth', 3.5);
        plot(zeros(size(x)), x, '--', 'Color', [0.6 0.6 0.65], 'LineWidth', 2.5);
        scatter(deflection_cm(1), x(1), 100, [0.3 0.9 0.5], 'filled', ...
                'MarkerEdgeColor', 'w', 'LineWidth', 1.5);
        scatter(deflection_cm(end), x(end), 100, [0.9 0.3 0.4], 'filled', ...
                'MarkerEdgeColor', 'w', 'LineWidth', 1.5);
        xlabel('Lateral Deflection (cm)', 'FontWeight', 'bold', ...
               'Color', [0.85 0.85 0.9]);
        ylabel('Spine Position (cm)', 'FontWeight', 'bold', ...
               'Color', [0.85 0.85 0.9]);
        title('Side View: Spine Curvature Profile', ...
              'FontWeight', 'bold', 'Color', [0.9 0.9 0.95]);
        margin2 = 0.5;
        xlim([min(deflection_cm) - margin2, max(deflection_cm) + margin2]);
        ylim([0, spineLength]);
        legend({'Deviation Area', 'Loaded Spine', 'Neutral (0° load)', ...
                'Lumbar base', 'Shoulders'}, 'Location', 'northwest', ...
               'TextColor', [0.85 0.85 0.9], ...
               'Color', [0.2 0.21 0.23], 'FontSize', 9);
        set(gca, 'GridColor', [0.3 0.3 0.35], 'GridAlpha', 0.4);
        grid on; hold off;

        %  output metrics (no extra blank line) 
        line1 = '╔══════════════════════════════╗';
        line2 = '║   PERFORMANCE METRICS        ║';
        line3 = '╚══════════════════════════════╝';

        spineSection = sprintf(['┌─ Spine Biomechanics ─────────┐\n' ...
                               '│ Max Deflection: %6.2f cm     │\n' ...
                               '│ Angular Dev:    %6.2f°       │\n' ...
                               '│ R1 (<1 cm):     %s│\n' ...
                               '└──────────────────────────────┘'], ...
                               max_deflection_cm, max_angle_deg, r1TextPadded);

        strapSection = sprintf(['┌─ Strap Analysis ─────────────┐\n' ...
                               '│ Excess Length:  %6.1f cm     │\n' ...
                               '│ Total Length:   %6.1f cm     │\n' ...
                               '│ Efficiency:     %6.1f%%       │\n' ...
                               '│ Safety Factor:  %6.2f        │\n' ...
                               '│ Strap Force:    %6.1f N      │\n' ...
                               '└──────────────────────────────┘'], ...
                               excessStrap, strapLength, efficiency, ...
                               safetyFactor, strapForce);

        pressSection = sprintf(['┌─ Pressure Analysis ──────────┐\n' ...
                               '│ Shoulder:       %6.2f kPa    │\n' ...
                               '│   Status: %-18s │\n' ...
                               '│ Chest:          %6.0f Pa     │\n' ...
                               '└──────────────────────────────┘'], ...
                               shoulderPress, getPressureStatus(shoulderPress), chestPress);

        durabilitySection = sprintf(['┌─ Durability ─────────────────┐\n' ...
                                    '│ Deformation:    %6.3f cm     │\n' ...
                                    '│ Obstructions:   %d            │\n' ...
                                    '│ Total Weight:   %6.3f kg     │\n' ...
                                    '└──────────────────────────────┘'], ...
                                    deform, obstruct, totalWeight);

        researchSection = sprintf(['┌─ Research Basis ─────────────┐\n' ...
                                  '│ El Masri et al. (2012)       │\n' ...
                                  '│ Lee et al. (lumbar stiffness)│\n' ...
                                  '│ Wettenschwiler et al. (2017) │\n' ...
                                  '└──────────────────────────────┘']);
        statsStr = sprintf('%s\n%s\n%s\n%s\n\n%s\n\n%s\n\n%s\n\n%s', ...
                          line1, line2, line3, spineSection, strapSection, ...
                          pressSection, durabilitySection, researchSection);

        set(params.statsText, 'String', statsStr);
    end

    % helper func
    function status = getPressureStatus(pressure)
        if pressure < 16
            status = 'Optimal';
        elseif pressure < 20
            status = 'Acceptable';
        elseif pressure < 35
            status = 'Discomfort';
        else
            status = 'Pain Risk';
        end
    end
end

